### PR TITLE
update CourseExamConfiguration model

### PR DESCRIPTION
**Pull request by varshamenon4**
**JIRA:** Related to [MST-1523](https://2u-internal.atlassian.net/browse/MST-1523).

**Description:** Updates the CourseExamConfiguration model so that course_id is unique, so that each course only has one CourseExamConfiguration.

**Author concerns:** Is there any reason why we wouldn't want the course_id to be unique?

**Merge checklist:**
- [x] All reviewers approved
- [x] CI build is green
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [x] Commits are squashed

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @varshamenon4!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.




:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Review by ashultz0 — APPROVED** [review]
looks like it does what it says

**Review by Zacharis278 — APPROVED** [review]
make sense to me

**Comment by openedx-webhooks** [comment]
@varshamenon4 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-exams&entry.867055334=https://github.com/edx/edx-exams/pull/28&entry.1484655318=https://github.com/varshamenon4&entry.752974735=2022-07-26+18:05&entry.1917517419=2022-07-26+20:21&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
